Monadic hooks
japgolly/scalajs-react pull request #1101
Opened 2024-12-16 19:49 UTC by rpiaggio

Implements an alternative syntax for hooks, in the form of:

``` scala
val component = ScalaFnComponent[Int] { props =>
  for {
    state       <- useState(props)
    _           <- useEffect(state.modState(_ + 1))
    forceUpdate <- useForceUpdate
  } yield
    <.div(
      state.value,
      <.button(^.onClick --> forceUpdate, "Click me")
    )
}
```

This provides a simpler syntax, while still guaranteeing safeguards to honor the rules of hooks: hook invocations are delayed and can only be invoked by `ScalaFnComponent`.

Source compatibility is preserved with the builder-style hooks.

2024-12-17 17:07 UTC, toddburnside approved these changes
The syntax is a great improvement. It will be easier to use and much easier to create custom hooks. 🎊 Should `Hooks.md` be updated? We probably need the existing documentation for awhile for existing code, but it could be at the bottom and marked as legacy? I don't see why someone would want to develop new code with the old syntax once this is available. 😄

2024-12-17 17:07 UTC, toddburnside commented on library/ghpages/src/main/scala/ghpages/examples/HooksExample.scala
> +  // def useAddReporter(initial: Int): HookResult[Reusable[Int => Callback]] ={
Did you want to keep this commented code?

2024-12-17 18:48 UTC, rpiaggio commented on library/ghpages/src/main/scala/ghpages/examples/HooksExample.scala
> +  // def useAddReporter(initial: Int): HookResult[Reusable[Int => Callback]] ={
Nope, just removed it, thank you

2024-12-17 18:57 UTC, rpiaggio commented
> The syntax is a great improvement. It will be easier to use and much easier to create custom hooks. 🎊 Should `Hooks.md` be updated? We probably need the existing documentation for awhile for existing code, but it could be at the bottom and marked as legacy? I don't see why someone would want to develop new code with the old syntax once this is available. 😄

Since this a beta branch, I was planning to give this a bit more of a test before officially documenting it, in case there are changes. After we have it in the wild for some time, we can decide how to document both styles.

2024-12-18 02:22 UTC, japgolly commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/react18.scala
> +// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause
Whoops, this should be removed.

2024-12-18 02:25 UTC, japgolly commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/HookResult.scala
> +    HookResult(f(a))
Ah so this is how users can still create `ScalaFnComponent` instances without hooks. Clever! Makes me think we should rename `HookResult` then because hooks are not always involved. Maybe something like `FnCompBody` (or similar but less ugly)?

2024-12-18 02:35 UTC, japgolly requested changes
I feel like a monadic approach was considered in the early days but there was a significant disadvantage to it. Something about safety that was lost (meaning there was a React-imposed requirement that I was able to enforce at the compiler-level with the existing approach, but would become a potential user-error with a mondaic approach)? I don't remember with enough detail. Looking at the code though, this monadic approach looks pretty good. In fact, it looks very nice. 👍

Impressive!

Only other two concerns are 1) documentation update (as you've already mentioned), and 2) binary backwards-compatibility — could I hear your position on it breaking? How concerned are you? Why / why not?

2024-12-18 13:23 UTC, rpiaggio commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/react18.scala
> +// For license information see LICENSE or https://opensource.org/licenses/BSD-3-Clause
Yup, sorry. I tested this out first on one of our projects and then copied the file over.

2024-12-18 13:25 UTC, rpiaggio commented on library/package.json
> +}
You have to have `jsdom` installed in npm for tests to run. I thought it practical to have this here and just `npm install` in order to be able to run tests.

2024-12-18 13:29 UTC, rpiaggio commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/HookResult.scala
> +    HookResult(f(a))
The driving thought for naming this was to have a nice signature for custom hooks, which are now defined so:

```scala
def myHook(input: Foo): HookResult[Bar]
```

In the case of rendering without hooks, the name of `HookResult` doesn't leak to the user, so I thought it was ok. But you are right in that it's not precise. Maybe we can use `Output`, which seems to fit both cases and is still kind of nice to read in code?

Custom hooks would then look like:
```scala
def myHook(input: Foo): Output[Bar]
```

Or, we can even have a type alias `type HookResult[A] = Output[A]`.

2024-12-18 13:49 UTC, rpiaggio commented
> I feel like a monadic approach was considered in the early days but there was a significant disadvantage to it. Something about safety that was lost (meaning there was a React-imposed requirement that I was able to enforce at the compiler-level with the existing approach, but would become a potential user-error with a mondaic approach)? I don't remember with enough detail.

I've been trying to remember if we considered this, but can't remember either. We probably considered it but didn't consider delaying evaluation, which is what makes it safe.

That said, you can still break the rules (eg: `fold`ing over an `Option` would allow you call hooks conditionally). But I think it's still safer than free-form and it's a small price to pay for the reduced syntax.

> Looking at the code though, this monadic approach looks pretty good. In fact, it looks very nice. 👍

Thank you!

> Only other two concerns are 1) documentation update (as you've already mentioned), 

I'll add to the PR. Not sure how to handle the availability of both styles.

> and 2) binary backwards-compatibility — could I hear your position on it breaking? How concerned are you? Why / why not?

If we make this part of a major release (`3.0.0`), it wouldn't be unexpected to have a breaking change. Since it's still source-compatible, this would have a very minor impact since it would just require recompiling downstream libraries with no need for code changes.

2024-12-18 22:23 UTC, rpiaggio commented
I ended up renaming to `Delayed`, which actually describes what the type class is doing, and added a `HookResult` type alias to implement a nice API.

I also documented the new style as the default style for hooks, making it explicit that there are ways around the rules; while keeping the builder-style as an alternative that provide complete safety while being more verbose.

2024-12-20 04:54 UTC, japgolly commented on doc/HOOKS_BUILDER.md
> +If you have a spare 9 hours (!), you can watch the livestreamed coding sessions
🤣🤣🤣

2024-12-20 05:02 UTC, japgolly commented on doc/HOOKS.md
> +    ExampleHook.useTitleCounter // <--- usage
I'm thinking better to demonstrate this with a for-comp for consistency and clarity.

2024-12-20 05:03 UTC, japgolly commented on doc/HOOKS.md
> +val newCustomHook: CustomHook[Unit, O] = CustomHook.fromHookResult(useHook2)
Very nice facilitating and demonstrating interop here 👍

2024-12-20 05:07 UTC, japgolly commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/component/Delayed.scala
> +class Delayed[+A](protected[react] val eval: () => A) extends AnyVal {
Ah this clarifies something for me: this is exactly the same in spirit as `CallbackTo` — the functionality is the same. It is also not stack-safe. Could we drop this in favour of `CallbackTo`?

2024-12-20 05:08 UTC, japgolly commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/package.scala
> +  type HookResult[A] = Delayed[A]
missing covariance

2024-12-20 05:15 UTC, japgolly requested changes
reviewed, feedback above

2024-12-20 13:18 UTC, rpiaggio commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/hooks/package.scala
> +  type HookResult[A] = Delayed[A]
good catch

2024-12-20 13:19 UTC, rpiaggio commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/component/Delayed.scala
> +class Delayed[+A](protected[react] val eval: () => A) extends AnyVal {
Yes! I thought of using `CallbackTo` initially, but I'm not sure we want to interop. Also, I agree it should be stack stafe.

I'll explore if we can unify code and report back.

2024-12-20 16:26 UTC, rpiaggio commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/component/Delayed.scala
> +class Delayed[+A](protected[react] val eval: () => A) extends AnyVal {
Well, we can't directly use `CallbackTo` without a major reshuffle, since `CallbackTo` is not available in `core`.

I tried implementing via `DefaultSync`, but found out we can't use `DefaultSync` in `core` because it becomes hard-linked.

So, I moved `Trampoline` to `util` and implemented `Delayed` in terms of `Trampoline`, just like `CallbackTo` does. Anyway, we probably don't want a lot of the thiings that `CallbackTo` provides, like timing, prompts, etc. This way we can ensure the minimal functionality we actually need here, plus not mixing the types, without involving `Delayed` with generic effects.

2024-12-23 03:05 UTC, japgolly commented on library/coreGeneric/src/main/scala/japgolly/scalajs/react/component/Delayed.scala
> +class Delayed[+A](protected[react] val eval: () => A) extends AnyVal {
Ok that sounds like a perfect trade-off. Thanks for working through that.

2024-12-23 03:10 UTC, japgolly approved these changes
LGTM. Nice work!

2024-12-23 13:26 UTC, merged