Builder helpers for adding an object containing attributes and a Ref function
japgolly/scalajs-react pull request #843
Opened 2021-01-17 16:38 UTC by rpiaggio

We are needing these when creating facades for libs that return attributes or ref functions to be applied to children components, so maybe someone else finds them useful.

Example: https://github.com/rpiaggio/scalajs-react-beautiful-dnd/blob/master/facade/src/main/scala/react/beautifuldnd/Draggable.scala#L38

2021-01-17 23:01 UTC, japgolly requested changes

2021-02-15 19:12 UTC, rpiaggio commented on core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
> +    for ((k, v) <- JsUtil.objectIterator(o) if !except.contains(k)) addAttr(k, v)
Sorry for the delay, right after sending the PR I went on holiday and then it took me a while to catch up.

Change #1 wouldn't work for the intended case, which is the "child function" pattern where a 3rd party component passes us an object with attributes. We don't know beforehand which attributes are present there.

(Examples: https://github.com/maslianok/react-resize-detector#3-child-function-pattern, https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/api/droppable.md).

The `except` is mainly needed to filter out a potential `style` property, which we want to add to the builder via `addStylesObject`.

Sending a commit with the other requested changes.

2021-02-15 19:14 UTC, rpiaggio commented on core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
> +  def addRefFn[A]    : RawRefFn[A]                          => Unit
:+1: (It was added to separate the abstract `val`s from the `def`)

2021-03-01 20:59 UTC, japgolly commented on core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
> +    for ((k, v) <- JsUtil.objectIterator(o) if !except.contains(k)) addAttr(k, v)
All good! Hope you had an awesome holiday :D

Re (1), my suggested change would still support your use case (and more) like this `addAttrsObject(o, _ != "style")`, wouldn't it? It might even allow for catching more cases if you change to something like `addAttrsObject(o, !_.equalsIgnoreCase("style"))`

2021-03-01 21:04 UTC, rpiaggio commented on core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
> +    for ((k, v) <- JsUtil.objectIterator(o) if !except.contains(k)) addAttr(k, v)
Yup, sorry for that, when I read it I probably saw `allowAttr` and skipped the definition 🤦‍♂️  . I'll add a commit.

2021-03-01 21:13 UTC, japgolly commented on core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
> +    for ((k, v) <- JsUtil.objectIterator(o) if !except.contains(k)) addAttr(k, v)
Ah makes sense. Thanks! :smiley:

2021-03-01 21:14 UTC, rpiaggio commented on core/src/main/scala/japgolly/scalajs/react/vdom/Builder.scala
> +    for ((k, v) <- JsUtil.objectIterator(o) if !except.contains(k)) addAttr(k, v)
I added a default `_ => true` so caller don't have to bother with that parameter if they want to add everything from the object.

2021-05-12 13:59 UTC, rpiaggio commented
Hi @japgolly , I think I have addressed the requested changes, did I miss something?

2021-05-17 21:24 UTC, japgolly commented
Sorry @rpiaggio , I've got so many different things going on that I missed this completely. I'll take a look at this later today

2021-05-18 05:35 UTC, japgolly commented
LGTM & thanks for your patience

2021-05-18 05:35 UTC, merged