Add monocle3 module
japgolly/scalajs-react pull request #862
Opened 2021-02-19 18:02 UTC by cquiroz

Monocle 3 is already available as RC1. It is a big release with API breaking changes so I think it maybe better on its own module

Monocle 3 is dotty compatible as well.

2021-03-01 21:06 UTC, japgolly commented on project/Build.scala
> +    val Monocle3Cats          = "3.0.0-M1"
You said in PR desc that `RC1` is available but here it's `M1`. Typo?

2021-03-01 21:07 UTC, japgolly commented on project/Build.scala
> +    val Monocle3Cats          = "3.0.0-M1"
Also can you please rename from `Monocle3Cats` to just `Monocle3` (seeing as there's no Scalaz version)

2021-03-01 21:07 UTC, japgolly commented on project/Build.scala
> +    .configure(commonSettings, publicationSettings, extModuleName("monocle3-cats"), hasNoTests)
`s/monocle3-cats/monocle3/` pls

2021-03-01 21:07 UTC, japgolly commented on project/Build.scala
> +    .configure(commonSettings, publicationSettings, extModuleName("monocle3-cats"), hasNoTests)
And the line above

2021-03-01 21:08 UTC, japgolly requested changes
-

2021-03-01 23:01 UTC, cquiroz commented
There is a new release of monocle 3 i’ll try to update it at the same time

2021-03-03 13:24 UTC, cquiroz commented
Ok I updated the PR with your suggestions and also monocle got updated to version 3.0.0-M3

This change makes some breaks with the old api so I copied the `internal` package to `monocle3` to fix it and also remove some warnings.

I'll add a few comments inline

2021-03-03 13:25 UTC, cquiroz commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleExtStateSnapshot.scala
> +  final class InstanceWithReuse[A](private val self: StateSnapshot.InstanceMethodsWithReuse[A]) extends AnyVal {
I think this could be removed in `monocle3`. WDYT

2021-03-03 13:26 UTC, cquiroz commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleSetter.scala
> +  def replace[S, B](l: O[S, S, _, B]): B => S => S
In `monocle3` `set` was renamed to `replace` and I'm following that change here

2021-03-03 13:26 UTC, cquiroz commented on project/Build.scala
> -  lazy val monocle = project
I'm not sure if this is needed anymore

2021-03-03 13:43 UTC, julien-truffaut commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleModifier.scala
> +  def modify[S, T, A, B](l: O[S, T, A, B]): (A => B) => S => T
I am not sure this is needed anymore since we introduced inheritance between optics. 
So you can ask for a `Setter` and pass a `Lens`.

2021-03-05 06:29 UTC, japgolly requested changes

2021-03-05 06:29 UTC, japgolly commented on project/Build.scala
> -  lazy val monocle = project
Yeah it's been long enough that we can get rid of that now but let's remove it in a separate PR. A separate PR will allow me to publish 1.7.8 with Monocle 3 support and remove the old `monocle` module in 1.8.0. Plus it makes the commits more atomic which is also nice.

2021-03-05 06:29 UTC, japgolly commented on build.sbt
> -val monocle       = ScalajsReact.monocle
Pls restore. See comment below.

2021-03-05 06:29 UTC, japgolly commented on monocle3/src/main/scala/japgolly/scalajs/react/MonocleReact.scala
> +  // Not using the Cats instance because it brings many other typeclasses into the output JS
Awesome! Thanks for the comment.

2021-03-05 06:29 UTC, japgolly commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleExtStateSnapshot.scala
> +  final class InstanceWithReuse[A](private val self: StateSnapshot.InstanceMethodsWithReuse[A]) extends AnyVal {
I think we should leave this in place for two reasons.

1. So that users reaching for it, find it, and are pointed to a working solution (as opposed to users spending time thinking they're imports are wrong, or thinking it's accidentally missing and then adding it locally and/or submitting a PR.
2. So that I or someone else, doesn't attempt re-add this a few years later, not realising how it would be very subtly broken.

2021-03-05 06:29 UTC, japgolly commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleModifier.scala
> +  def modify[S, T, A, B](l: O[S, T, A, B]): (A => B) => S => T
Yes!! :heart: I would love to see this removed, it will greatly simplify all the surrounding code.

@julien-truffaut I love your decision to use inheritance in Monocle 3 btw. I never agreed with the FP dogma against subtyping in Scala (and variance too for that matter) that was spread back in the day. I'm very happy to see it receding in the Scala FP community lately and I think it's going to make Monocle 3 more accessible. :+1:

2021-03-05 06:29 UTC, japgolly commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleOptionalModifier.scala
> +trait MonocleOptionalModifier[O[_, _, _, _]] {
This can all go in the bin too :tada:

2021-03-05 06:29 UTC, japgolly commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleSetter.scala
> +  def replace[S, B](l: O[S, S, _, B]): B => S => S
Moot because this can all go in the bin now thanks to inheritance in Monocle 3.

2021-03-14 21:28 UTC, julien-truffaut commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleModifier.scala
> +  def modify[S, T, A, B](l: O[S, T, A, B]): (A => B) => S => T
Great, I am happy you like the direction Monocle is going. Optics creation is going to be drastically simplified too.

2021-03-15 00:32 UTC, cquiroz commented on monocle3/src/main/scala/japgolly/scalajs/react/internal/MonocleExtComponent.scala
> +    def modStateL[A, B](L: PSetter[S, S, A, B])(f: A => B, cb: Callback = Callback.empty): F[Unit] =
An commented me can simplify this using Monocle 3 inheritance, in this case `PSetter` and for `Option` we can use `PTraversal`

2021-03-22 03:19 UTC, japgolly commented
Hey @cquiroz , just to confirm: is this ready for merge? LGTM so far.

2021-03-22 03:26 UTC, japgolly commented
Ah also @cquiroz , could you please also just add a quick note to `doc/changelog/1.8.0.md`

2021-03-22 03:52 UTC, cquiroz commented
The PR should be ready to merge, it maybe nice that before you make another release we verify whether there are newer versions as they are showing up regularly.

2021-03-22 04:01 UTC, japgolly commented
> Ah also @cquiroz , could you please also just add a quick note to doc/changelog/1.8.0.md

Cool just this then ^^

Also I think there's some button you're supposed to click   as the PR status still shows me *"Changes Requested"*.

> it maybe nice that before you make another release we verify whether there are newer versions as they are showing up regularly

Yeah np we'll keep it up-to-date once merged.

2021-03-22 04:08 UTC, cquiroz commented
I update the changelog. I think you need to accept the change as you requested it. I'm not sure where though.

2021-03-22 04:46 UTC, merged

2021-03-22 04:46 UTC, japgolly commented
Yeah I'm not sure either. Oh well good enough! Merged & thx

2021-03-23 01:13 UTC, japgolly commented
Hey @cquiroz @julien-truffaut According to https://repo1.maven.org/maven2/com/github/julien-truffaut/monocle-core_sjs1_2.12/ Monocle 3.0.0-M3 isn't published for Scala 2.12. Unfortunately there's a bug in the CI script here that resulted in going green here. Any plans to release Monocle 3 for Scala 2.12?

2021-03-23 11:40 UTC, julien-truffaut commented
Yeah we dropped Scala 2.12. It is too painful to maintain more than 2 Scala versions. It is already a pain to support 2.13 and 3 but it is a necessity.

Except if we get corporate sponsorship, I am really against making more effort in supporting older Scala versions. I almost stopped open source developement because of that.

2021-03-24 22:31 UTC, japgolly commented
@julien-truffaut Yeah I understand completely. :100: